jsonata-js/jsonata

- package.json
There were some extra things in the `package.json` file which look like they are no longer needed.
> Clean up the package.json file

- jsonata.js
This allows `jsonata.js` to be loaded a browser without exposing its internal functions/variables.
A side-effect is the generated jsdoc no longer includes those internal functions etc. I've found lots of questions on StackOverflow as to how to get jsdoc to pickup such functions, but no real solution.
> Wrap jsonata in closure to prevent leakage of internal variables

- .eslintignore
- .gitignore
- package.json
- `uglify-js` is used for minification
- the minified version generated after a successful test phase
> Publish a minified version of JSONata

- jsonata.js
- test/jsonata-test.js
Fixes issue #94 
The error was generated by the $clone() function when attempting to clone the array.  The function signature needed updating.
> $clone() must work with arrays as well as objects

- jsonata.js
- test/jsonata-test.js
Largely internal changes to how singleton sequences are stored and passed around in the evaluator.  A few tests modified to accommodate the change of behaviour - mostly edge cases.
This PR should resolve #93
> Changes to how 'singleton sequences' are handled

- jsonata.d.ts
I'm including a very basic `ExprNode` type.  Eventually, I hope to provide a much more detailed version as an algebraic sum type.
Signed-off-by: Michael M. Tiller <michael.tiller@gmail.com>
> Added the `ast` method to the expression

- jsonata.js
resolves #127 & #128 
remove call to parseFloat() in isNumeric()
remove extraneous argument in call to apply()
> remove extraneous code

- CHANGELOG.md
- package.json
> update changelog and publish v1.5

- .npmignore
Configure .npmignore to include `jsonata.d.ts` in npm package
resolves #182
> publish typescript definition file

- jsonata.js
- test/test-suite/groups/function-string/case001.json
Change numeric precision from 13 to 15 in function `$string`
resolves #194
> $string should format numbers to 15 s.f.

- jsonata.js
Simplify the numeric checks as suggested in issue #184 
resolves #184
> simplify integer rounding

- src/jsonata.js
- test/test-suite/groups/comments/case000.json
- test/test-suite/groups/comments/case000.jsonata
- test/test-suite/groups/comments/case001.json
- test/test-suite/groups/comments/case001.jsonata
- test/test-suite/groups/comments/case002.json
- test/test-suite/groups/comments/case002.jsonata
- test/test-suite/groups/comments/case003.json
- test/test-suite/groups/comments/case003.jsonata
> Add support for comments in expression

- src/jsonata.js
- test/test-suite/groups/boolean-expresssions/case017.json
- test/test-suite/groups/boolean-expresssions/case018.json
- test/test-suite/groups/boolean-expresssions/case019.json
- test/test-suite/groups/boolean-expresssions/case020.json
- test/test-suite/groups/boolean-expresssions/case021.json
- test/test-suite/groups/boolean-expresssions/case022.json
- test/test-suite/groups/boolean-expresssions/case023.json
- test/test-suite/groups/boolean-expresssions/case024.json
- test/test-suite/groups/boolean-expresssions/case025.json
- test/test-suite/groups/boolean-expresssions/case026.json
operands of Boolean operators (and/or) should be treated as false if undefined
resolves #246
> operands of and/or operators should be treated as false if undefined

- src/jsonata.js
- test/test-suite/groups/literals/case018.json
- test/test-suite/groups/literals/case019.json
> more robust check for sequence property

- CHANGELOG.md
- package.json
Update changelog and release 1.6.0 to npm.
> release v1.6.0

- src/jsonata.js
- test/async-function.js
> fix concurrency bug in ~>

- test/test-suite/groups/function-tomillis/case004.json
> Fix error with ambiguous timezone in tests.

- docs/object-functions.md
- src/jsonata.js
- test/run-test-suite.js
- test/test-suite/groups/function-error/case000.json
- test/test-suite/groups/function-error/case003.json
- test/test-suite/groups/function-error/case005.json
- test/test-suite/groups/function-error/case006.json
- test/test-suite/groups/function-error/case009.json
- test/test-suite/groups/function-error/case010.json
Continuation of #351 
* More test cases for $error()
* Add documentation for $error() function.
> More $error() functionality

- docs/higher-order-functions.md
- src/functions.js
- src/jsonata.js
- test/test-suite/groups/hof-single/case000.json
- test/test-suite/groups/hof-single/case001.json
- test/test-suite/groups/hof-single/case002.json
- test/test-suite/groups/hof-single/case003.json
- test/test-suite/groups/hof-single/case004.json
- test/test-suite/groups/hof-single/case005.json
- test/test-suite/groups/hof-single/case006.json
- test/test-suite/groups/hof-single/case007.json
- test/test-suite/groups/hof-single/case008.json
- test/test-suite/groups/hof-single/case009.json
- test/test-suite/groups/hof-single/case010.json
> Add $single() function.

- docs/string-functions.md
- src/functions.js
- src/jsonata.js
- test/test-suite/groups/function-string/case023.json
- test/test-suite/groups/function-string/case024.json
- test/test-suite/groups/function-string/case025.json
- test/test-suite/groups/function-string/case026.json
- test/test-suite/groups/function-string/case027.json
- test/test-suite/groups/function-string/case028.json
Implements proposal discussed in #334
> Add prettify option to $string() function.

- docs/array-functions.md
- docs/comparison-operators.md
- src/functions.js
- src/jsonata.js
- src/utils.js
- test/test-suite/groups/comparison-operators/deep-equals.json
- test/test-suite/groups/function-distinct/distinct.json
Upgrade the equality operators `=` and `!=` to do deep equality comparison.
Add `$distinct()` function to return sequence of values with duplicates removed
Resolves #117
> Add function $distinct()

- .travis.yml
- package.json
- src/parser.js
update versions
Fix new lint error
> drop node v6; update dev dependencies

- src/jsonata.js
- test/test-suite/groups/transforms/case013.json
- test/test-suite/groups/transforms/case014.json
Attempted to delete a property from a non-object value. 
Resolves #396 
> check that target is an object before deleting property

- CHANGELOG.md
- package.json
release bug fix for timezone processing
> release v1.8.1

- CHANGELOG.md
- package.json
> release v1.8.2

- src/functions.js
- src/jsonata.js
- test/test-suite/groups/flattening/large.json
> rewrite array flattening to avoid RangeError

- src/functions.js
- test/test-suite/groups/boolean-expresssions/case027.json
- test/test-suite/groups/function-signatures/case001.json
> $not on empty sequence should return empty sequence

- CHANGELOG.md
- package.json
> release v1.8.3

- jsonata.d.ts
arguments, name, procedure were missing from types
> Adding missing type properties

- src/datetime.js
- test/test-suite/groups/function-tomillis/parseDateTime.json
> Implement timezone support for $toMillis

- CHANGELOG.md
- package.json
> Release v1.8.4

- CHANGELOG.md
- package.json
> Release v1.8.5

- docs/programming.md
> (docs) Add an example for ternary conditional

- CHANGELOG.md
- package.json
> Release v1.8.6

- .github/workflows/jsonata.yml
> Publish docs

- docs/predicate.md
> Fix typo in predicate.md

- docs/overview.md
I couldn't find any overview of available implementations, so I created this one.
The place right under "Get JSONata" looks right for this.
> Added overview of languages implementing JSONata

- .github/workflows/jsonata.yml
Update GitHub Actions workflow to support a v1 branch for backported fixes.
> Update workflow to support v1 branch

- CHANGELOG.md
- package.json
Publish version 1.8.7 with backported fix
> Publish version 1.8.7

- docs/overview.md
Add pure Python implementation available at https://github.com/rayokota/jsonata-python
> Add pure Python implementation

- docs/overview.md
Impl is compatible with the latest 2.0.5 features
> Update Java implementation version
