jsonata-js/jsonata

README.md
This makes is clear that the project currently has no (dev) dependencies, and would highlight any outdated ones if they were ever added.
=> Add david-dm dependency badge

jsonata.js, test/jsonata-test.js
Adding a `$exists` function to the JSONata function library that returns false if its argument is `undefined`, otherwise it returns true. This can be used to determine whether an item in the JSON data provided exists. Function takes one parameter only.
=> Add $exists function

functions.md, jsonata.js, test/jsonata-test.js
Added to the casting functions the usual condition that invoking them on undefined (no match) should return undefined
=> cast functions: undefined arg returns undefined

README.md
The `david-dm` dependency badge seems to not be working more than it is; I think their servers are struggling, but in turn it just gives an ugly `image not found` on the front page of this repo.
As there are no dependencies, the badge is only indicating as such, and is not actually making anyone aware of out of date dependencies (as you would see when it's used elsewhere). I think it should be removed for now, and could return in the future if any dependencies are added.
=> Remove dependency badge

jsonata.js, test/jsonata-test.js
The position of the error is already provided as a property of the error, and it is not tested.
It is hard to post-process the errors if the message string contains a position.
=> Error strings should not contain duplicate position

.eslintrc
Also:
- banned used of `console`, e.g. `console.log()`
- currently the project follows the `1tbs` brace style, so added a rule to stop anyone doing anything different in the future
=> ESLint updates, principally to ban eval()

.eslintrc, jsonata.js, test/.eslintrc
The `'use strict'` directive is only recognised as the beginning of a script or function.  If JSONata is merged with other files using `browserify` or similar technology, the global `'use strict'` at the top of the file will cease to apply as it will no longer be the first statement in the file.  Therefore it is safer to put `'use strict'` at the start of the JSONata main function, so that it is guaranteed to apply to that function and other functions defined within it.  This is not necessary for the test code, which retains a global `'use strict'`.
=> Use function version of 'use strict'

README.md, jsonata.js, test/jsonata-test.js, tutorial.md
User feedback suggests that the mechanism for creating 'grouped' objects versus arrays of objects is confusing.  Currently creating a grouped or merged object is done using the following syntax:
`location.path.{key: value}`
and the syntax for creating arrays of objects is:
`location.path.[{key: value}]`
The confusion arises because the `.` operator is really a 'map' higher order function, so the expectation is that each value in the array on the LHS of `.` should produce a value in a result array without the need for any array syntax.  The function that processes this `.` operator has special case handling for .{} to enable this grouping, and that is probably a Bad Thing. 
So I have removed this 'special case' code and now `location.path.{key: value}` behaves like `location.path.[{key: …
=> Changes to behaviour of object constructor and result arrays

README.md
GitHub's markdown (including it's support for HTML) doesn't support embedding videos in pages, so the current attempt to embed a YouTube video is showing up fine on npm but not on GitHub. The solution discussed widely online is to use an image (generated by YouTube) with a link instead, which will work on both GH and npm.
=> Replace broken YouTube video embed with image+link

jsonata.js, test/jsonata-test.js
The following expression binds a variable $foo, then overrides it in a nested scope.  It should return undefined because `bar` matches nothing in the input.  However, it incorrectly returns 'foo'.
```
(
$foo := 'foo';
(
$foo := bar;
$foo
)
)
```
This incorrect behaviour only occurs when overriding with `undefined` because of an error in the lookup code.
=> fix variable scope when overridden by undefined

.npmignore
Adding a `.npmignore` file so that the package published to npm contains only the files needed when installed. That is, `jsonata.js`, `package.json`, the license and the readme.
=> Add .npmignore to remove unnecessary files from npm package

jsonata.js
This change updates the tokenization of two character operators to be the same as for single character operators.  It reduces the lines of code required, aiding readability.  It uses `hasOwnProperty()` rather than multiple `if()`s, as is the pattern for single character operators.  This may have slightly different performance characteristics, but is unlikely to make a significant difference as `hasOwnProperty()` is already called for almost all tokenization.
=> Simplify tokenization of two-char operators

.eslintrc, jsonata.js
JSONata mostly uses `===` and equivalent operators instead of the `==` operators.  This is good because it avoids a whole class of potential errors.  This PR adds a check for this via the ESLint `eqeqeq` rule, and fixes up instances where the rule had not been applied.
=> Add ESLint eqeqeq rule to JSONata

jsonata.js, test/jsonata-test.js
These simple string<->base64 functions are helpful when constructing basic auth headers.
The code in this pull request provides trivial implementations that should work in both a browser (where btoa and atob) functions are available, and in a Node.js runtime where these are available via Buffer.
A further extension would be to support binary<->base64, but I'm not sure of:
- The right representation of binary in a JSONata structure (or if this is defined yet)
- How to distinguish the expected return value, when decoding a string. Should that be a different function name?
=> Base64 encode (btoa) and decode (atob) functions

jsonata.js, test/async-function.js
The following error occurs when jsonata is invoked with a callback and an expression that returns a `null` value:
```
TypeError: Cannot read property 'then' of null
at evaluate (jsonata.js:1377:58)
at next (native)
at evaluateStep (jsonata.js:1476:31)
at next (native)
at evaluatePath (jsonata.js:1429:38)
at next (native)
at evaluate (jsonata.js:1323:34)
at next (native)
at Object.evaluate (jsonata.js:4117:33)
at test/async-function.js:20:14
at jsonataPromise (test/async-function.js:19:12)
at Context.<anonymous> (test/async-function.js:95:23)
```
=> Correctly handle null values when executed with a callback

.babelrc
IE 11 and PhantomJS do not support ES6 features such as `Symbol` and it looks like I didn't configure `.babelrc` to pull in the polyfill for this feature.
Unfortunately this bloats `jsonata-es5.js` even further, from 212kB to 277kB. `jsonata-es5.min.js` now increases from 53kB to 85kB. So this is just a temporary instant fix for now, until I figure out how to pull in only the `Symbol` polyfill by itself and nothing else.
=> Include the Babel polyfill

.travis.yml
According to the node.js LTS schedule v8.x is now the current release and will become the LTS release in October, so it would be good to start testing JSONata against it now. Equally, v5.x is neither a current release or an LTS (v4.x is in maintenance, v6.x is active) and likely has little usage so it can be dropped from the list.
Also switching to `'4'` from `'4.4'` to pick up latest v4.x release instead of v4.4.x.
=> Adopt node 8 in Travis, drop node 5

jsonata.js, package.json, test/async-function.js, test/jsonata-test.js
ESLint was previously pinned at v2 because that's the highest that node 0.10 supported, but since node 0.10 was dropped in JSONata v1.2, we can update to ESLint v4.
There are a few new breaking rules, which require some human
intervention.
There are some other npm modules which could do with updating, and this is best left to https://greenkeeper.io/
=> Update ESLint to v4

jsonata.js, test/jsonata-test.js, test/parser-recovery.js
Fixes https://github.com/jsonata-js/jsonata/issues/73
The `S0202` message currently reports the internal token type, rather than the token value.  For some tokens that's ok (because they are the same), but for `name` and `literal` tokens at least, it's better for the user to see the values that they typed, rather than the confusing `(name)` and `(literal)`.
=> Write out token value, not internal type

jsonata.js, test/jsonata-test.js
As suggested in #55, there is a requirement to convert between ISO 8601 formatted timestamps (like those generated by the `$now()` function) and milliseconds since epoch (as generated by `$millis()`).
This PR adds two new functions, `toMillis(<timestamp_string>)` and `fromMillis(<number>)`, to do this.
Pulling this into the `1.4` branch for now so that it can be rolled up with the other changes and new functions for that release.
=> Add new functions to convert between ISO 8601 timestamps and milliseconds since epoch

.travis.yml
Now that node.js 8 is LTS and 9 is latest the testing should be expanded to include the new version. Version 7 has dropped out of support, so removing to save Travis cycles.
This could be done against `master`, but including on this branch so it doesn't fall behind again unnecessarily.
=> Start testing against node.js 9

package.json
Keeping `devDependencies` update to date by moving up to a new major version (`4.x.x`) of `mocha`.
=> Update to latest major version of mocha

test/jsonata-test.js
Some test cases reverse the expected
result and the actual result.  Furthermore,
a handful of other tests use the term
expected to refer to an actual result.
These changes just clarify these cases.
Signed-off-by: Michael M. Tiller <michael.tiller@gmail.com>
=> Fix reversed test cases

.vscode/settings.json
This just initiates some project level settings for VSCode.  In this case, I just wanted to turn off `formatOnSave` because it might cause unnecessarily cosmetic changes if everybody formats the code according to different style guidelines.
Of course, this should not impact people who are not using VSCode.
=> Establish some (common) VS code settings (for those using it)

jsonata.d.ts, package.json
This eliminates the need to install `@types/jsonata` and corrects a few issues in those type definitions as well.  Specifically, the callback arguments for `evaluate` were missing, I've added
them in.  Also, the signature for the `assign` function was wrong (it only allowed functions to be
bound the variables), that is also fixed.  Finally, the `registerFunction` method on compiled
expressions was completely missing, I've added that as well.
I've tested this by removing `@types/jsonata` as a dependency from my TypeScript project
and then installing this version of `jsonata` from my local file system.  Not only are the type
definitions correctly located by the TypeScript compilers, but the errors I had associated with
some of the problems with the previous type definitions are also gone.
=> Adding TypeScript definitions directly in package

jsonata.js
I noticed that `getSymbol` could fall through without returning any value.  The expected return type is a string, but without this default case, it can return `undefined`.
Also, added an extra guard to an if statement to ensure that `contextRegex` is really defined.  I see that they are (currently) defined together.  But the TypeScript compiler flagged this as a potential issue.  Seems reasonable to put this guard in place just in case at some future the "defined together" behavior changes.
=> Missing default case

package.json
Fixes #105 
Signed-off-by: Matt Chapman <mpchapman@gmail.com>
=> provide es5 as main entry point, es6 as module entry point

package.json
This slight change to `package.json` creates a new script called `mocha`.
Invoking `npm run mocha` allows **only** tests to be run (no lint, no coverage, etc).
This doe not change the behavior of `npm test` at all, it simply adds a new script
that can be used to invoke only tests.
Signed-off-by: Michael M. Tiller <michael.tiller@gmail.com>
=> Establish a way to run only tests

package.json
New major versions of `browserify` and `mocha` have been introduced; behaviour appears unchanged in local testing.
=> Dependency updates for mocha and browserify

jsonata.js, test/test-suite/groups/function-append/case005.json
Fixed $append bug([#139](https://github.com/jsonata-js/jsonata/issues/139)).
=> fix $append function side-effect

jsonata.js
I left a comment in https://github.com/jsonata-js/jsonata/pull/141 when I was originally using a regex string I'd sourced elsewhere, but due to the issues I ran into I ended up crafting my own string; removing the comment as it would be more confusing that the regex no longer matches the one on the referenced URL.
=> Remove leftover comment

CHANGELOG.md, package.json
- Update `$toMillis()` to allow more complete range of ISO 8601 compatible dates (issue #140)
- Fix `$append()` so that it doesn't mutate the first argument (issue #139)
=> update changelog and publish 1.5.1

jsonata.js, test/test-suite/groups/lambdas/case012.json
If the body a lambda function ends with a function call, it gets replaced by a thunk so as not to grow the stack at runtime (allowing tail recursion).  If the function call is followed by a predicate, then it is not a tail-call, and should not be replaced.  The check for this is missing and has been added by this PR.
=> Fix tail-call optimiser for predicated function invocations

jsonata.js, test/test-suite/groups/errors/case018.json, test/test-suite/groups/variables/case012.json
The left hand side of the binding operator `:=` must be a variable.  This PR moves the validation of this rule from the evaluator (which throws a dynamic error) to the parser (throws a syntax error).  This is also more robust since it is checking against the token type rather than a node in the AST.
Resolves #148 which was ignoring the predicate attached to the variable in the AST.
=> move validation of LHS of := from evaluator to parser

test/test-suite/groups/tail-recursion/case008.json, test/test-suite/groups/tail-recursion/case009.json
Issue #137 raised the question (I believe) as to whether lambda function signatures survive the tail-call optimization process, and hence get validated at runtime.  This PR contains a test case that demonstrates that it does.  A tail recursive function has been written such that its initial invocation conforms to the signature, but inside the function it invokes itself with an invalid argument.  The validation fails as expected.  A variant of this test has also been added which passes validation throughout.
=> test signature validation of tail recursive function

jsonata.js, test/test-suite/groups/function-formatNumber/case033.json, test/test-suite/groups/function-formatNumber/case034.json, test/test-suite/groups/function-formatNumber/case035.json
In `$formatNumber`, the `zero-digit` character should be used to pad left or right of the decimal separator and in the exponent.  At the moment it uses `0` even if `zero-digit` has been overridden.
Resolves #161
=> $formatNumber should use zero-digit character for padding

jsonata.js, test/test-suite/groups/function-formatNumber/case036.json
Add usual `undefined` handling to `$formatNumber` function
Resolves #165
=> handle undefined inputs in $formatNumber

test/implementation-tests.js, test/test-suite/groups/function-clone/case000.json, test/test-suite/groups/function-clone/case001.json, test/test-suite/groups/function-clone/case002.json, test/test-suite/groups/transforms/case012.json
This PR removes all tests that use the `$clone()` function from the language-agnostic test suite and replaces them with JavaScript tests.
The `$clone()` function was added to jsonata-js solely as a workaround for Node-RED. It's not required by other implementations and therefore should not be included in the standard tests.
=> Move clone test cases to the JavaScript test suite.

.gitignore, jsonata.js, test/run-test-suite-async.js, test/test-suite/groups/hof-filter/case002.json
Created a test driver to run the test suite in async mode
Fixed all failing test cases.  These all involved functions which needed to asynchronously invoke the evaluator (such as the higher-order functions, the sort syntax & function chaining operator)
resolves #217
=> async driver for full test suite, and fix all failing cases

jsonata.js, test/implementation-tests.js, test/run-test-suite-async.js, test/run-test-suite.js, test/test-suite/groups/matchers/case000.json, test/test-suite/groups/matchers/case000.jsonata, test/test-suite/groups/matchers/case001.json
The four functions `$match`, `$contains`, `$split` and `$replace` can take a regex argument.  The regex syntax `/.../` is in fact just some syntactic sugar for a higher-order function that generates a 'matcher' function.  This matcher function, when invoked on a string, will return a well defined structure (which I haven't documented yet :blush:) which describes the match(es).  It was designed so that these four functions could work with any pluggable matching scheme, not just the built-in regex, provided the matcher returned the correct object structure.  That's the theory, but I never got round to testing it.  This PR fixes that.  Custom matchers can now be implemented in jsonata as lambdas or as external javascript functions.
Resolves #213
=> add support for custom matcher functions

jsonata.js
Minor change to remove reliance on lastIndex in the global RegExp object.
resolves #205
=> regex no longer relies on global state (lastIndex)

jsonata.js, test/test-suite/groups/function-substring/case008.json, test/test-suite/groups/function-substring/case009.json, test/test-suite/groups/function-substring/case010.json, test/test-suite/groups/function-substring/case011.json, test/test-suite/groups/function-substring/case012.json, test/test-suite/groups/function-substring/case013.json, test/test-suite/groups/function-substring/case014.json, test/test-suite/groups/function-substring/case015.json, test/test-suite/groups/function-substring/case016.json, test/test-suite/groups/function-substring/case017.json, test/test-suite/groups/function-substring/case018.json
The fix for #156 introduced a regression into the `$substring` function when dealing with negative values of start parameter (count from end of string).  This was caused by a miscalculation of the end position.  Also added checks to prevent start position and length from going below zero, in line with the previous behaviour.
Resolves #204
=> $substring should handle negative start position and length

jsonata.js
As discussed in issue #164, the third argument of the internal `apply()` function should never be passed the `environment` structure.  In cases where this occurs, I've replaced it with `null`.  This has no effect of any of the tests.
Resolves #164
=> third argument of apply() should not be environment

.travis.yml
As of the end of April node `10.x` as replaced `9.x` as the latest release.
As `9.x` is a non-LTS release it drops off support really quickly, so we no longer need to test against it, but we should be testing against `10.x` which becomes the LTS in October.
=> Get Travis to test against node 10.x

jsonata.js, test/parser-recovery.js, test/test-suite/groups/sorting/case014.json, test/test-suite/groups/sorting/case015.json, test/test-suite/groups/sorting/case016.json, test/test-suite/groups/sorting/case017.json, test/test-suite/groups/sorting/case018.json, test/test-suite/groups/sorting/case019.json
For the case where a path expression with a sort expression as the first step is applied to input data with a top level array, then an unhandled javascript error gets passed back to the user.  There are three separate parts to this fix:
1. The sort function needs to be more tolerant of receiving non-arrays
2. The parser needs to flag the sort expression as one that doesn't iterate over its input (much like the array constructor)
3. The flag in step 2 needs to bubble up through `block` nodes in the AST.
Resolves #210
=> fix sort syntax when applied as first step in path to an input array

.eslintignore, .gitignore, package.json, src/jsonata.js
Continues from #231. This one probably warrants a little debate.
Okay so the basic observation from #214, #211 and #202 is that several consumers are attempting to directly consume `./jsonata.js`, which currently makes use of the ES6 generator syntax, which does not have good support. The solution to this problem is to [compile the ES6 generator syntax away at build time using Babel](https://babeljs.io/docs/plugins/transform-regenerator), so that `./src/jsonata.js` can still use generators while the output file `./jsonata.js` does not. However, compiling the ES6 generator syntax away also requires us to pull in JSONata's first-ever third-party dependency, `regenerator-runtime`.
With this PR,
* The `npm` task `copy`, which simply copied `./src/jsonata.js` to `./jsonata.js`, is removed.
* …
=> Packaging fixes, phase two

test/implementation-tests.js, test/test-suite/groups/descendent-operator/case015.json, test/test-suite/groups/descendent-operator/case016.json, test/test-suite/groups/descendent-operator/case017.json, test/test-suite/groups/function-each/case000.json, test/test-suite/groups/function-keys/case000.json, test/test-suite/groups/function-keys/case001.json, test/test-suite/groups/function-spread/case001.json, test/test-suite/groups/wildcards/case000.json, test/test-suite/groups/wildcards/case006.json, test/test-suite/groups/wildcards/case007.json, test/test-suite/groups/wildcards/case008.json, test/test-suite/groups/wildcards/case009.json
This PR addresses issue [#179: Test suite relies on JavaScript object traversal](https://github.com/jsonata-js/jsonata/issues/179).
- Six tests in the test suite have a new "unordered" flag indicating that their results are not in a fixed order.
- Two tests have been moved from the language-agnostic test suite to the JavaScript test file.
Note: In the two cases where test files were deleted, subsequent files were renamed to avoid gaps in the numbering. For example, after deleting the wildcard test file `case006.json`, `case007.json` was renamed to `case006.json` and `case008.json` was renamed to `case007.json`. This might be overkill. Perhaps it would be better to keep these filenames consistent across releases.
=> Indicate tests that return unordered arrays.

src/jsonata.js
This is a change to resolve a `TODO` in the code for error `T0412` where the argument supplied to a function that operates on arrays contains an array of different types to what was specified in the function signature. At present is just returns the symbol (`a`, `s`, etc.), but it should return an English string that is more descriptive; that is, the full plural of the type (`arrays`, `strings`, etc.)
We expose this error straight through to the user in the UI in App Connect so we wanted to make it clearer why they should not be using `$join()` (for example) with an array of objects.
I've tried to go for the simplest implementation here just using a static object that the error object references with a key; this could become a function if we wanted to add more protection, but as the key …
=> Translate symbol in array type error to full plural of type

package.json, src/jsonata.js, test/implementation-tests.js
Fixes #261.
I fixed this by modifying (simplifying) `lookupMessage`.
* `lookupMessage` is now named `populateMessage`. Rather than return a string, it now populates `err.message` as a side-effect (or leaves it as is, if appropriate).
* Generally speaking, `populateMessage` now explicitly expects `err` to be either
1. a plain old JavaScript object with an error `code`, thrown by `jsonata` itself, whose `message` should be populated using the appropriate template, or
2. an actual `Error` object or similar (such as a `DOMException`) with no `code`, but with an existing `message` property which should not be touched.
Note that logic which automatically reified an error message of `"Unknown error"` was untested and therefore apparently unused, and so has been removed. The only way to hit this …
=> Handle DOMExceptions

src/jsonata.js, test/test-suite/groups/function-eval/case000.json, test/test-suite/groups/function-eval/case001.json, test/test-suite/groups/function-eval/case002.json, test/test-suite/groups/function-eval/case003.json, test/test-suite/groups/function-eval/case004.json, test/test-suite/groups/function-eval/case005.json, test/test-suite/groups/function-eval/case006.json, test/test-suite/groups/function-eval/case007.json
New function `$eval(expr [, input])`
Parses and evaluates the string `expr` which contains literal JSON or JSONata expression using the current context as the context for evaluation.
Optionally override the context by specifying the second parameter
resolves #134 
=> $eval function

src/jsonata.js, test/test-suite/groups/flattening/case042.json, test/test-suite/groups/flattening/case043.json, test/test-suite/groups/flattening/case044.json
'keep array' syntax `[]` should apply to any expression type, not just location paths.
resolves #236
=> keepArray syntax should apply to all expression types

src/jsonata.js, test/test-suite/groups/transforms/case012.json
The 'update' part of the transform syntax should only allow JSON objects to be specified.  However, arrays were being accepted because a JS array is an object.  An extra check was added.
resolves #245
=> check for object should not include arrays

src/jsonata.js, test/implementation-tests.js, test/test-suite/groups/function-each/case001.json, test/test-suite/groups/function-sift/case003.json, test/test-suite/groups/function-sift/case004.json, test/test-suite/groups/hof-filter/case003.json, test/test-suite/groups/hof-map/case009.json
The handling of optional arguments for the function arg passed to $filter, $each & $sift should be consistent with the correct behaviour in $map.
resolves #233 
resolves #250
=> consistent handling of function params for HOFs

CHANGELOG.md, package.json
Release patch to fix generated `jsonata-es5.js` (https://github.com/jsonata-js/jsonata/pull/284)
=> Release version 1.6.2

package.json, polyfill.js, src/utils.js
Changes made to the es5 build and polyfills to get jsonata-es5.js up to scratch for running the test suite in Java Nashorn.  This is representative of a barebones ES5 implementation.
Most of the tests now run under nashorn with the exception of:
- tests involving multibyte unicode strings (might need extra polyfills here)
- case insensitive regexes (for some reason)
- base64 encode/decode functions
resolves #287 (hopefully)
=> fix ES5 build to run test suite in nashorn

polyfill.js
Extra function needs to be polyfilled in order for jsonata-es5.js to work in IE11.
Note that the online exerciser won't work in IE11 as a result of this since that uses jsonata.js rather than jsonata-es5.js.
=> extra polyfill required for IE11

src/functions.js, src/jsonata.js, src/utils.js, test/implementation-tests.js
The fix for #247 introduced a significant performance regression.
This PR rewrites that bit of code to recover the loss.
=> Fix performance regression

src/functions.js, test/test-suite/groups/function-each/case002.json
`$each()` returns an array of values by applying a supplied function to each name/value pair in a given object.  If that function returns `undefined` (no match / empty sequence), then that `undefined` value is getting added to the result sequence.  It shouldn't - it should be flattened out.
=> $each should not result in undefined values in the result object

docs/contributing.md
Fixes https://github.com/jsonata-js/jsonata-js.github.io/issues/11
Small doc update to explain how to request an invite to the Slack workspace, both to fix the above issue and as this came up again as an issue recently.
=> Add details on how to get Slack invite to docs

src/jsonata.js, test/implementation-tests.js, test/run-test-suite-async.js, test/run-test-suite.js, test/test-suite/groups/errors/case025.json, test/test-suite/groups/errors/case026.json
The tail-call trampolining code was masking the true location (position & token) of the error. 
resolves #297
=> fix error inserts generated in functions

src/jsonata.js, test/test-suite/groups/range-operator/case021.json, test/test-suite/groups/range-operator/case022.json, test/test-suite/groups/range-operator/case023.json, test/test-suite/groups/range-operator/case024.json
Impose implementation defined limit of 1e7 to the size of array that can be allocated by the range operator (`..`)
resolves #240
=> limit size allocated by range operator to 1e7

src/functions.js, src/jsonata.js, test/test-suite/groups/function-error/case000.json, test/test-suite/groups/function-error/case001.json, test/test-suite/groups/function-error/case002.json, test/test-suite/groups/function-error/case003.json, test/test-suite/groups/function-error/case004.json, test/test-suite/groups/function-error/case005.json, test/test-suite/groups/function-error/case006.json, test/test-suite/groups/function-error/case007.json, test/test-suite/groups/function-error/case008.json, test/test-suite/groups/function-error/case009.json, test/test-suite/groups/function-error/case010.json
Proposed in https://github.com/jsonata-js/jsonata/issues/167
Implementation notes:
* Used error code `D3137` for all errors thrown with this function since it was the next number in the sequence (for dynamically thrown errors from functions).
* There is no template text for this error.
* Message is optional.  Defaults to `$error() function evaluated`
=> Add $error() function.

docs/string-functions.md, src/functions.js, src/jsonata.js, test/test-suite/groups/function-decodeUrl/case000.json, test/test-suite/groups/function-decodeUrl/case001.json, test/test-suite/groups/function-decodeUrl/case002.json, test/test-suite/groups/function-decodeUrlComponent/case000.json, test/test-suite/groups/function-decodeUrlComponent/case001.json, test/test-suite/groups/function-decodeUrlComponent/case002.json, test/test-suite/groups/function-encodeUrl/case000.json, test/test-suite/groups/function-encodeUrl/case001.json, test/test-suite/groups/function-encodeUrl/case002.json, test/test-suite/groups/function-encodeUrlComponent/case000.json, test/test-suite/groups/function-encodeUrlComponent/case001.json, test/test-suite/groups/function-encodeUrlComponent/case002.json
=> Add URL/URI Helper Functions

src/functions.js
In recent versions of NodeJS the old calls to the Buffer class (e.g. `Buffer(str, 'binary')`) have been deprecated in favour of new functions (see https://nodejs.org/api/buffer.html#buffer_new_buffer_array). In fact, it's been deprecated through all of the versions of NodeJS that JSONata supports.
This is a simple replacement which should give the same functionality but get rid of the deprecation warnings.
=> Replace deprecated Buffer call

docs/higher-order-functions.md, src/functions.js, src/jsonata.js, test/test-suite/groups/hof-reduce/case009.json, test/test-suite/groups/hof-reduce/case009.jsonata, test/test-suite/groups/hof-reduce/case010.json, test/test-suite/groups/hof-reduce/case010.jsonata
The second argument can now be an arity-4 function with the following signature
`myfunc($accumulator, $value[, $index[, $array]])`
resolves #102
=> Enhance $reduce to support 4 arg function

src/functions.js, test/test-suite/groups/function-number/case027.json, test/test-suite/groups/function-number/case028.json, test/test-suite/groups/function-number/case029.json, test/test-suite/groups/function-number/case030.json
Allow numeric strings to have leading zeros when casting to numbers in `$number()`
resolves #368
=> allow leading zeros when casting string to number

docs/sorting-grouping.md
Link should be `path-operators#order-by-` not `control-operators#order-by`
=> Fix deadlink for order-by in docs

src/jsonata.js, src/parser.js, test/test-suite/groups/joins/index.json
Fix code and test cases (+ add more) for tuple generating syntax (joins) on top level arrays
resolves #382 
=> fix generation of tuple stream from input arrays

src/datetime.js, src/jsonata.js, test/test-suite/groups/function-parseInteger/parseInteger.json
`$parseInteger` is missing a check that is in `$formatInteger`
resolves #387 
=> check for unsupported sequence in parseInteger

test/test-suite/groups/parent-operator/errors.json
Added a bunch of tests for the parent operator, basically making sure that `%%` and `%%%` error out so they are open for future use in the language.
=> Add more error tests for parent operator

src/jsonata.js, test/test-suite/groups/flattening/sequence-of-arrays.json, test/test-suite/groups/hof-zip-map/case002.json, test/test-suite/groups/hof-zip-map/case003.json
The `[]` syntax in a path expression should output the result sequence as an array even if the sequence contains one value (singleton sequence).  However, this is not happening if that value is an array.  Instead it's just using that as the result array.  This PR fixes that, so that it will be enclosed in another array.
Resolves #399 
=> Maintain singleton sequence of array

src/datetime.js
The test suite failures are caused by careless use of non-UTC Date functions in the date/time parser
resolves #403 
=> fix test suite to work in all timezones

src/jsonata.js, test/test-suite/groups/regex/case037.json, test/test-suite/groups/regex/case038.json
When partially applying the $match function, the regex was compiled and stored in the closure.
The same RegExp object was then applied multiple times in the $map, but the lastIndex property was not being reset, so alternate matches would fail (which then resets lastIndex to 0).
This PR fixes that.
resolves #427 
=> Reset lastIndex on RegExp objects that get reused in closures

src/functions.js, test/test-suite/groups/function-string/case029.json
Fixes a regression when the $string() function is applied to a top-level array causing the output to be enclosed in an additional array
=> unpack outer wrapper in $string()

docs/regex.md
Node.js v14.3.0 was used to verify my change.
❯ node
Welcome to Node.js v14.3.0.
Type ".help" for more information.
> const rx = /[a-z]*an[a-z]*/i;
> const string = 'A man, a plan, a canal, Panama!';
> string.match(rx);
[
'man',
index: 2,
input: 'A man, a plan, a canal, Panama!',
groups: undefined
]
In spite of 'i' commonly being used for case insensitive matching, the 'i' modifier is non-performant when matching against large strings. In practice it's better to include both upper and lower cases using standard regular expression class syntax, e.g.: /[a-zA-Z]*[aA][nN][a-zA-Z]*/. This is functionally equivalent to what you currenty have, but it avoids the expensive 'i' modifier.
Consider including an aside to explain this so your readership (who may be unfamiliar with the intracacies of …
=> Fix error in generic matcher example

jsonata.d.ts
Rather than the union, just marking fields optional is cleaner as they all share `type`. This reduces the TS error complexity as well.
=> Further Refine / Simply ExprNode type

src/jsonata.js, test/test-suite/groups/function-eval/case008.json
The logic for handling the second parameter to this function should be the same as for handling the input to any expression.
This includes wrapping a top level array input in a singleton sequence so it gets treated as a single input.
This code was missing from this function and is added here.
resolves #463 
=> $eval() - array inputs should be wrapped

src/jsonata.js, test/parser-pluggable-regex.js
*Motivation:*
I would like to use JSONata with [node-re2](https://github.com/uhop/node-re2) - a regex node.js implementation that guards against backtracking. 
This - in combination with work like https://github.com/jsonata-js/jsonata/pull/478 - will make it easier for me to run user-supplied JSONata in a sandbox. 
The specific attack I'm looking to guard against is an [ReDoS](https://nodejs.org/en/docs/guides/dont-block-the-event-loop/#blocking-the-event-loop-redos)
=> feat(regex): Add support for pluggable regex engines for use in evaluation

website/siteConfig.js
For https://github.com/jsonata-js/jsonata/issues/497
Bringing the copyright date up-to-date as per the issue raised.
=> Update copyright date in docs

src/jsonata.js, test/test-suite/groups/boolean-expresssions/case028.json, test/test-suite/groups/boolean-expresssions/case029.json, test/test-suite/groups/boolean-expresssions/case030.json
My first ever PR to an open-source project. Woo!
Fixes #338 and #505.
Defers execution of the right-hand side of boolean expressions. Uses the natural short-circuiting behavior of Javascript's `||` and `&&` operators to evaluate only when needed.
=> Make boolean operators short-circuit

jsonata.d.ts
While working with the library I encountered the following missing properties from the ExprNode type definition.
* `expressions` exists when type is `block`
* `lhs` and `rhs` exist when type is `binary`
=> Add missing properties to ExprNode type definition

src/jsonata.js, test/test-suite/groups/array-constructor/array-sequences.json
Change the logic for promoting a singleton sequence of array type into an array of arrays.  The logic was put in to fix issue #399 but caused an unintended regression as described in issue #462.
resolves #462
=> fix regression with singleton sequence of array type

.travis.yml
Spotted in the recent Travis runs that it was testing with versions 8, 10 and 12; 8 went out of support in April 2020, and 10 in April 2021, and so can be dropped from support (or at least from active testing). Things like node-red also require 12, as has become quite common across a lot of packages.
So switching this to go with:
- 12 (Maintenance LTS)
- 14 (Active LTS)
- 16 (Current major version, next LTS in October)
@andrew-coleman Arguably this should be a major version bump, as dropping Node.js version support is a breaking change (it's something I've seen seen quite a few packages on npm do, and we're also doing internally). However, I think we might want a discussion on versioning rather than doing that right now with this.
=> Update nodejs versions in Travis

src/datetime.js, test/test-suite/groups/function-tomillis/case010.json, test/test-suite/groups/function-tomillis/case011.json, test/test-suite/groups/function-tomillis/case012.json
Width formatting doesn't appear to be respected without a separator. Corresponding issue: https://github.com/jsonata-js/jsonata/issues/546
JSONata `1.8.5`
Node `v14.17.0`
Reference spec for width formatting: https://www.w3.org/TR/xpath-functions-31/#date-time-examples
At the moment, it appears the width formatting is not honored within `$toMillis` due to the way the regex is being generated. For an example input `201802`, I should be able to specify a matcher `[Y0001][M01]` which will result in a parsed value of `2018/02/01`. At the moment, the library incorrectly grabs too many characters due to the `+` regex so I end up with `20180/02/01`
| Input | Picture | Output (timestamp) | Output (pretty) |
| --- | --- | --- | --- |
| 201802 | `[Y0001][M01]` | 1517443200000 | Thu, 01 Feb 2018 …
=> toMillis: Allow width formatting without separators

src/functions.js
I've been seeing a warning for `DeprecationWarning: Buffer() is deprecated due to security and usability issues.`. This fixes that.
=> Fixed Buffer Deprecation warning

README.md
Originally opened as a test that Travis triggers, but actually probably worth removing this dead link to a now-removed YouTube video from the readme
=> Remove dead tech talk link

.github/workflows/jsonata.yml
Node.js 18.x is now the current LTS version and so should be the one most people are now running or moving to, so we should run the tests against it to support it.
Would have been good to stop 12.x, as it's been out of support for a while, but that's best done on a major version bump and I just missed the boat on that one! Can remove 12 and 14 together when 14 goes out of support in April for 3.0.0.
=> Test on Node.js 18

README.md
This updates the examples in the README to follow the new v2.0.0 API, and to match the docs at http://docs.jsonata.org/using-nodejs and http://docs.jsonata.org/using-browser
Signed-off-by: Andy Edwards <andy.edwards@uk.ibm.com.com>
=> Update examples in README for v2.0.0 API

jsonata.d.ts
=> fix(type): fix return type of evaluate method

jsonata.d.ts
- Converted lhs into an array of ExprNode (optional with empty array)
- Added options as parameters for jsonata
Signed-off-by: Dishant Kaushik [dkaushik95@gmail.com](mailto:dkaushik95@gmail.com)
---
Related issue: https://github.com/jsonata-js/jsonata/issues/585
=> Fix TS definitions

src/datetime.js, test/test-suite/groups/function-fromMillis/formatDateTime.json
Fixes #574
Updates [$fromMillis() function](https://docs.jsonata.org/date-time-functions#frommillis) to support am/pm `PN` presentation format to output AM/PM and adds test cases for `PN` and `Pn` (existing test case for default presentation covers just `P`).
Note: I did not implement [PNn] for Am/Pm, it's not shown in the examples https://www.w3.org/TR/xpath-functions-31/#date-time-examples so I assumed it's not commonly used and did not implement it to keep the fix simple. Happy to revisit that if needed.
Signed-off-by: Alex Woodgate <ajwoodgate@gmail.com>
=> Add upper/lower presentation format for am/pm in fromMillis

docs/overview.md
jsonata-rs is an actively-developed fork of jsonata-rust.
=> Add new Rust implementation

src/jsonata.js, test/implementation-tests.js
Port of https://github.com/jsonata-js/jsonata/pull/676 to the v1 stream
=> Prevent writing to the object prototype or constructor (v1 port)

.github/workflows/jsonata.yml
Also run testing on Node.js 20.x as the current LTS version.
12, 14 and 16 are out of support (18 keeps going for another year) so might want to consider dropping them at some point, but that should be done as part of a major version bump.
=> Update workflow for Node.js 20

src/functions.js, test/test-suite/groups/lambdas/case013.json
A lambda function is represented internally as a javascript object.  A check needs to be added to the `lookup` function to only expose properties if they are a non-function object.  Similar to the check that already exists in the `keys` function.
Resolves #691
=> Prevent lookup of function object properties

jsonata.d.ts, src/jsonata.js, test/implementation-tests.js, test/run-test-suite.js
Fixes https://github.com/jsonata-js/jsonata/issues/695
These two internal/undocumented APIs are very useful in debugging scenarios and for imposing time/depth constraints on queries. However, this internal API should only be accessible when configuring an expression programmatically and not from inside a query. Otherwise, a query can be manipulated to remove such diagnostics or constraints. Addressing this could potentially protect consumers with certain use cases from targeted attacks.
By changing both binding keys to `Symbol`, they can no longer be accessed inside of the query since the Symbol API is not accessible there. Without access to the Symbol, a query is fundamentally unable to address these bindings.
I am building a pluggable and security-minded framework around JSONata (open …
=> Protect `__evaluate_entry` and `__evaluate_exit` callbacks

src/jsonata.js, test/implementation-tests.js
This is a small change to add a new hook, similar to `__evaluate_entry` and `__evaluate_exit`, but for when a new frame is created from an old one. I am building an open-source pluggable framework around JSonata, and this small change will open up an enormous amount of awesome possibilities.
It is beneficial for advanced cases like modifying env with additional metadata or mutating it so that you can analyse bind/lookup calls & provide diagnostics. I have actually _patially_ achieved this already to significant effect by hooking into the env on `__evaluate_entry`. However, in some cases inside the JSONata core, a new frame is created, which is then immediately bound to, and consequently that happens before it has yet to recurse through `evaluate` and the entry callback. That means that …
=> Add undocumented/private API to hook into when a new frame is created.

.github/workflows/jsonata.yml
Node.js 22 is now the active LTS version, so GitHub actions testing should be running on 22 as well as other versions. As the active LTS it probably makes sense to run the other actions on this version too.
At some point we may drop 12, 14 and 16 as they are out of support (and 18 too after April next year), but as they're still passing we can leave them for now. Dropping any of these versions should result in a major version bump.
=> Run tests on Node.js 22

src/datetime.js, test/test-suite/groups/function-tomillis/case013.json
If there are two adjacent integer definitions for date/time fields in the picture string without any extra markup between them, then the generated regex must precisely define the number of digits in the first field.
Resolves #727
=> Improve regex generation for DateTime parser

docs/higher-order-functions.md
https://github.com/jsonata-js/jsonata/issues/462 and https://github.com/jsonata-js/jsonata/issues/708 both reflect seemingly unexpected behaviour in how map works. 
At the very least - the current behaviour has been in there for several versions now and is completely undocumented. This heavily throws new-time readers and AI tools parsing the docs. 
This is my 5 min attempt to alleviate that issue. 
I am unsure on whether `undefined` is the right term for the empty array case - potentially that needs correcting. But regardless - something is better than nothing!
=> Reflect missing behaviours on map in docs
